export const MAIN_PAGE_ROUTE = '/'
export const SIGNUP_ROUTE = '/signup'
export const LOGIN_ROUTE = '/login'
export const PROFILE_ROUTE = '/profile'
export const ARTIST_ROUTE = '/artist'
export const SEARCH_ROUTE = '/search'